### ISSUE TITLE
MacOS Big Sur Support -- Empty Monarch Desktop Client.

### ISSUE THREAD

**Issue by amouxkin** [Dropsource/monarch#1]
The Monarch Desktop Client does not seem to support MacOS Big Sur.

**Comment by fertrig** [comment]
We'll be testing Monarch on Big Sur in the next few weeks. We should be able to get to it before Big Sur is officially released.

I'll leave this issue open to track the work. Thanks for the feedback, @amouxkin.

**Comment by amouxkin** [comment]
Thank you for the quick response @fertrig , I really this project and was wondering if there were any way to contribute ?

**Comment by fertrig** [comment]
I'm glad you like it! Someone from our team will reach out to see how you can help us out.

**Comment by amouxkin** [comment]
Great, looking forward to it.

**Comment by fertrig** [comment]
@amouxkin Monarch is now working on Big Sur.
