### ISSUE TITLE
Monarch only works on stable

### ISSUE THREAD

**Issue by gcostaapps** [Dropsource/monarch#11]
I was on dev branch and tried to run monarch and got this error.

```
Using flutter sdk at C:\flutter\bin\flutter
Found configuration errors:
- The flutter sdk version this project is using is not supported. Found version 2.1.0-12.2.pre.
```

Switched back to stable and got it running. I think that for now it's not a problem as dev is very close to stable but in the future switching branches just to run monarch may be a bit frustrating.

**Comment by fertrig** [comment]
I agree. We are looking into how to fix this issue. Are you on macos or windows?

**Comment by gcostaapps** [comment]
> I agree. We are looking into how to fix this issue. Are you on macos or windows?

Windows

**Comment by fertrig** [comment]
Monarch now support flutter versions across all channels 🥳

https://monarchapp.io/blog/version_1.0.3
