### ISSUE TITLE
VM initialization failed

### ISSUE THREAD

**Issue by overtube** [Dropsource/monarch#115]
`monarch --version`

```Dart SDK version: 2.19.4 (stable) (Tue Mar 7 09:58:46 2023 +0000) on "linux_x64"```

`moarch init`
```VM initialization failed: Invalid vm isolate snapshot seen```

`monarch run -v`

```VM initialization failed: Invalid vm isolate snapshot seen```

**Comment by overtube** [comment]
what I do wrong?

**Comment by fertrig** [comment]
Hi, please confirm you downloaded the latest monarch linux binaries from:

```
curl -O https://d148mrbia1nlbw.cloudfront.net/linux/monarch_linux_2.1.10.tar.xz
```

Then run `monarch --version`, its output should be something like:

```
$ monarch --version
Monarch version 2.1.10

Monarch modules:
- cli: 3.0.3
- controller: 1.3.1
- platform_app: 2.1.1
- preview_api: 2.3.0

Revision:
fb0f51b2d2cd719485f054d39b7a68349f2baf95
```

Then please make sure you are running `monarch init` inside a flutter project.

If you are getting the same error, please run `flutter doctor -v` and post the output here.
