### ISSUE TITLE
We could not find a compatible Monarch UI for this version of Monarch and Flutter.

### ISSUE THREAD

**Issue by jtmuller5** [Dropsource/monarch#119]
I am using the latest version of the stable channel for Flutter:
```
Flutter 3.13.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 367f9ea16b (34 hours ago) • 2023-09-12 23:27:53 -0500
Engine • revision 9064459a8b
Tools • Dart 3.1.2 • DevTools 2.25.0
```

When I try to run `monarch run`, I get the following error:
```
We could not find a compatible Monarch UI for this version of Monarch and Flutter.
You could try switching Flutter versions. Or, create a GitHub issue in the Monarch repo 
and let us know which Flutter version your project is using: 
https://github.com/Dropsource/monarch/issues
```

`monarch init` worked okay so its just the run command that seems to not like my Flutter setup.

**Comment by fertrig** [comment]
The automation failed yesterday when the new flutter release came out. I'm looking at it in a few minutes. 

Monarch should work with a previous version of Flutter.

**Comment by fertrig** [comment]
It should work now.
