### ISSUE TITLE
The display window is not opening correctly. 

### ISSUE THREAD

**Issue by princestha** [Dropsource/monarch#12]
I can see that the monarch app opens 2 windows, I am able to see the first one with the settings and list of the stories, but the second window, which I assume is the view window, is missing. I can see that it is open by looking at the taskbar but I am unable to locate that.  

P.S. I was able to locate it by connecting a different screen but it looks like it opens up on a separate screen, even if the second screen is not connected. Any ideas?

**Comment by fertrig** [comment]
Are you on mac or windows? The code asks the OS to open it right next to the first window, but the OS is really the one in control on how to arrange windows. 

I have seldom seen the behavior you are describing. Usually I find the window, I place it where I want it to be, then I quit Monarch, then launch it again. The OS should then place it where it was last closed from.

We are planning on adding a "dock" feature that will move the second window next to the first window.

**Comment by princestha** [comment]
Hi @fertrig I am on windows. Glad to hear you have also come across this issue. Yep, I think the dock feature or at least the option to dock would be very good. 
I tried to close the app and window and re-launch, but every time I do that, give me the same issue. 
BTW, a feature request I would like to ask, can you add scale to the windows. My resolution is 3480X2160, and when I am using the android emulator, if I make the window bigger it will scale accordingly, else the windows are far too small for me.

**Comment by fertrig** [comment]
We'll try reproducing your issue on Windows. We may be able to improve the window positioning.

The scaling is a good idea. We didn't do it before because resizing the window would crash the story window due to flutter desktop being unstable still. The flutter team may have fixed that issue now that flutter desktop is closer to stable. Resizing the story window is in our backlog now.

Also, thanks for your positive feedback!

**Comment by fertrig** [comment]
All the issues reported here should be fixed with the latest [release v1.2.1](https://monarchapp.io/blog/version_1.2.1).
