### ISSUE TITLE
Nothing happens after i type 'monarch run'.

### ISSUE THREAD

**Issue by spacekestrel** [Dropsource/monarch#13]
Output is this:
```
Using flutter sdk at C:\Work\SDK\flutter\bin\flutter
CreateProcessW failed 2

Starting Monarch

Preparing stories...
3.1sec elapsed, 0/2 tasks completed
6.2sec elapsed, 1/2 tasks completed
Preparing stories completed, took 7.0sec

Launching Monarch app...

Terminating running tasks...
Done
```

I'm using windows.

**Comment by princestha** [comment]
Are you seeing the icons on the taskbar in windows?

**Comment by fertrig** [comment]
Please run it with verbose flag:
```
monarch run -v
```
Feel free to send me the log file it generates: ftrigoso@dropsource.com

**Comment by gcostaapps** [comment]
@spacekestrel The same happened to me before installing Visual Studio 2019 as in the [docs](https://monarchapp.io/docs/install). Everything worked fine after installing it. I'm using Windows too. Maybe it's the same problem.

**Comment by spacekestrel** [comment]
> 
> 
> Please run it with verbose flag:
> 
> ```
> monarch run -v
> ```
> 
> Feel free to send me the log file it generates: [ftrigoso@dropsource.com](mailto:ftrigoso@dropsource.com)

sended

**Comment by spacekestrel** [comment]
> 
> 
> Are you seeing the icons on the taskbar in windows?

no, i don't.

**Comment by fertrig** [comment]
From the logs, the process failed because of `exit code -1073741515`. Please make sure the following requirement is installed:

> Make sure you have [Visual Studio 2019](https://visualstudio.microsoft.com/downloads/) (not to be confused with Visual Studio Code) with the “Desktop development with C++” workload installed, including all of its default components

**Comment by spacekestrel** [comment]
> 
> 
> From the logs, the process failed because of `exit code -1073741515`. Please make sure the following requirement is installed:
> 
> > Make sure you have [Visual Studio 2019](https://visualstudio.microsoft.com/downloads/) (not to be confused with Visual Studio Code) with the “Desktop development with C++” workload installed, including all of its default components

Wow. That not good requirement for a program such like this.

**Comment by fertrig** [comment]
Monarch uses a Flutter desktop window. That requirement is a Flutter desktop requirement.
