### ISSUE TITLE
could not find a compatible Monarch UI for this version of Monarch and Flutter.

### ISSUE THREAD

**Issue by chanjungkim** [Dropsource/monarch#142]
We could not find a compatible Monarch UI for this version of Monarch and Flutter.

I get this message after I run `monarch run`.
It used to work fine but I don't know why it doesn't run properly.

Here's the version info of mine.

Flutter 3.19.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 54e66469a9 (7 days ago) • 2024-04-17 13:08:03 -0700
Engine • revision c4cd48e186
Tools • Dart 3.3.4 • DevTools 2.31.1

--------

Monarch version 2.2.3

Monarch modules:
- cli: 3.0.5
- controller: 1.4.2
- platform_app: 2.1.1
- preview_api: 2.4.1

Revision:
d28ad143f21701fd67ecbf3d08bffd67de7bebcc

---------

And I am using monarch package - 3.8.0 version

I tried with different versions.
Flutter - stable/beta.
monarch version - 2.2.2/2.2.3
monarch package - 3.0.0/3.8.0
vm_service - 3.0.0/4.2.0

None of them worked for me.

**Comment by fertrig** [comment]
I'm sorry about that. Could you please try again?

**Comment by fertrig** [comment]
I deployed a fix a few days ago. If you have any more issues, please let me know.
