### ISSUE TITLE
No preview window on Windows 10, Flutter 3.24, Monarch 2.2.7

### ISSUE THREAD

**Issue by kylenoteboom** [Dropsource/monarch#149]
I run execute `monarch init` and `monarch run` in a fresh project (simple template from the flutter CLI that creates a new project :

```
flutter create monarch_test
cd monarch_test
monarch init
monarch run
```

Monarch does start and prepare and attach to stories, but no preview window pops up with the Monarch UI. Selecting a different story or preview device doesn't make the preview window appear either.

`Monarch --version` output:

```
Monarch version 2.2.7

Monarch modules:
- cli: 3.0.5
- controller: 1.4.2
- platform_app: 2.3.1
- preview_api: 2.4.1
```

`flutter --version` output:

```
flutter --version
Flutter 3.24.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 80c2e84975 (3 weeks ago) • 2024-07-30 23:06:49 +0700
Engine • revision b8800d88be
Tools • Dart 3.5.0 • DevTools 2.37.2
```

An initial look at the verbose logs indicated MSBuild missing, but installing that explicitly and additing its bin directory to the PATH didn't appear to change this behaviour.

I wasn't able to make much of the verbose logs yet, but please do find them attached:

[log_monarch_cli.log](https://github.com/user-attachments/files/16681424/log_monarch_cli.log)

Aside: a preview version (likely Flutter 3.19) worked fine on the exact same Windows installation, but I've not (yet) invested the time to try and get that working again.

**Comment by kylenoteboom** [comment]
As I mentioned, Flutter 3.19 does work. This required downgrading `environment.sdk` to `^3.3.0` and the `monarch` package to `^3.0.0` in pubspec.yaml. Additionally, I had to use monarch_cli (not sure that's the correct name, but it's the executable in the binary release the guide on the website directs users to download) version `2.2.3`.

[log_monarch_cli.log](https://github.com/user-attachments/files/16695135/log_monarch_cli.log)

No comparison  of the logs on my end yet, though.

**Comment by fertrig** [comment]
I'll run it soon to see what's going on. Thank you for the report.

**Comment by fertrig** [comment]
Fixed. I had to upgrade the dart sdk on the windows build machine. Monarch on Windows should work with Flutter 3.24.2.
