### ISSUE TITLE
`Flutter 3.24.4` Not Supported Yet

### ISSUE THREAD

**Issue by mg3994** [Dropsource/monarch#151]
```bash
$> monarch run 
Using flutter sdk at C:\src\flutter\bin\flutter

Downloading the Monarch UI for this project's flutter version...

We could not find a compatible Monarch UI for this version of Monarch and Flutter.
You could try switching Flutter versions. Or, create a GitHub issue in the Monarch repo
and let us know which Flutter version your project is using:
https://github.com/Dropsource/monarch/issues
```
# My current Flutter Version
```bash
Flutter 3.24.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 603104015d (3 days ago) • 2024-10-24 08:01:25 -0700
Engine • revision db49896cf2
Tools • Dart 3.5.4 • DevTools 2.37.3
```

**Comment by msiprime** [comment]
facing the same issue here...

**Comment by fertrig** [comment]
Hello. Sorry for the trouble. A couple of the build machines had rebooted incorrectly. I fixed the issue. 

Monarch is only going to support the latest Flutter version for now. To use monarch, please get on latest stable flutter (3.24.4), then run `monarch run` again.

**Comment by karthiKN-sk** [comment]
i am also facing the same issue here
`/karthikeyansk/fvm/versions/3.24.3/bin/flutter
Enabling Flutter for desktop

Downloading the Monarch UI for this project's flutter version...

We could not find a compatible Monarch UI for this version of Monarch and Flutter.
You could try switching Flutter versions. Or, create a GitHub issue in the Monarch repo 
and let us know which Flutter version your project is using: 
https://github.com/Dropsource/monarch/issues

Flutter 3.24.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2663184aa7 (8 weeks ago) • 2024-09-11 16:27:48 -0500
Engine • revision 36335019a8
Tools • Dart 3.5.3 • DevTools 2.37.3

Monarch version 2.2.7

Monarch modules:
- cli: 3.0.5
- controller: 1.4.2
- platform_app: 2.1.1
- preview_api: 2.4.1

Revision:
c5831d1176003a005bcc20ae70e9650be272f118
`

**Comment by fertrig** [comment]
Hello @karthiKN-sk. Please see my previous comment [here](https://github.com/Dropsource/monarch/issues/151#issuecomment-2441844080).
