### ISSUE TITLE
We could not find a compatible Monarch UI for this version of Monarch and Flutter.

### ISSUE THREAD

**Issue by Kmohitkumar** [Dropsource/monarch#152]
My Flutter and Dart Version :
Flutter 3.24.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2663184aa7 (7 weeks ago) • 2024-09-11 16:27:48 -0500
Engine • revision 36335019a8
Tools • Dart 3.5.3 • DevTools 2.37.3

Monarch version 2.2.7

Monarch modules:
- cli: 3.0.5
- controller: 1.4.2
- platform_app: 2.3.1
- preview_api: 2.4.1

Revision:
c5831d1176003a005bcc20ae70e9650be272f118

**Comment by Kmohitkumar** [comment]
[log_monarch_cli.log](https://github.com/user-attachments/files/17538163/log_monarch_cli.log)

**Comment by fertrig** [comment]
Hello. Sorry for the trouble. A couple of the build machines had rebooted incorrectly. I fixed the issue. 

Monarch is only going to support the latest Flutter version for now. To use monarch, please get on latest stable flutter (3.24.4), then run `monarch run` again.
