### ISSUE TITLE
FVM issue

### ISSUE THREAD

**Issue by blondie63** [Dropsource/monarch#19]
I'm using last fvm to have multiple flutter sdk and it works fine
But monarch send me this err:
mauro@iMac-di-Mauro test_monarch % monarch run      
Using flutter sdk at /Users/mauro/fvm/versions/2.2.0/bin/flutter
Found configuration errors:
- Could not determine flutter version or channel from command `flutter --version`

whats wrong ?

**Comment by fertrig** [comment]
Could you please run `monarch run -v` and send me the log file it generates? ftrigoso@dropsource.com

**Comment by fertrig** [comment]
We can reproduce the issue you are experiencing. It is related to this issue in FVM: https://github.com/leoafarias/fvm/issues/291

We are working on a workaround.

**Comment by fertrig** [comment]
We just [released](https://monarchapp.io/blog) a fix for this issue. To get the fix run `monarch upgrade`. 

When the Monarch CLI detects that a project is running on an unknown channel, it will try to find the project's flutter version in the stable, beta and dev channels.  It will then use that channel to fetch the corresponding Monarch UI.

**Comment by DonnC** [comment]
@fertrig 
Im still facing issues with fvm 
```
$ monarch run -v
Writing application logs to C:\Users\dell\AppData\Local\Temp\monarch_cli_849f12d8\log.txt
CreateProcessW failed 2
Using flutter sdk at C:\Users\dell\fvm\default\bin\flutter

Downloading the Monarch UI for this project's flutter version...

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 12.0M  100 12.0M    0     0  1547k      0  0:00:07  0:00:07 --:--:-- 1611k

Extracting Monarch UI zip... Error extracting Monarch UI zip.
Application logs written to C:\Users\dell\AppData\Local\Temp\monarch_cli_849f12d8\log.txt

```

**Comment by fertrig** [comment]
Please email me the log file.

**Comment by DonnC** [comment]
i realized the error came when i was using git bash, im trying with windows cmd and its proceeding on preparing stories

**Comment by fertrig** [comment]
I see. We'll test with git bash on windows. We may need to update our docs.
