### ISSUE TITLE
Building Instructions

### ISSUE THREAD

**Issue by vHanda** [Dropsource/monarch#23]
Hi. Could you please provide instructions on how to build monarch? I can't seem to figure it out.

Actually, I can't even seem to find the code I'm interested in. Is all of the code open source?

**Comment by fertrig** [comment]
Parts of Monarch are open sourced and parts of it are closed source. We might open source everything at some point. 

Monarch is a combination of applications: a CLI executable, native desktop apps, and a Flutter app. There is also the monarch flutter package. 

To achieve a good experience, every operating system has its own native desktop app. That is why we only support Windows and macOS at this point. We plan to begin work on Linux soon though. Stay tuned.
