### ISSUE TITLE
Migrate to null-safety

### ISSUE THREAD

**Issue by fertrig** [Dropsource/monarch#3]
We need a couple of dependencies to migrate to null-safety first. These are their issues:

- https://github.com/dart-lang/dart_style/issues/978
- https://github.com/dart-lang/source_gen/issues/493

Once both of those issues are resolved, we can migrate the monarch package.

**Comment by fertrig** [comment]
The dependencies above are migrated. Working on migrating the monarch code to null safety.

**Comment by princestha** [comment]
Just waiting for this to push so that I can start to utilize this. When are you expecting this to be ready? 

Thank you

**Comment by fertrig** [comment]
Working on it as we speak. I will post an update in a few hours.

**Comment by fertrig** [comment]
Done! You can find the details here: https://monarchapp.io/blog/version_0.3.6

Let me know how it goes.
