### ISSUE TITLE
Monarch is incompatible with MobX codegen

### ISSUE THREAD

**Issue by nikitakalpakovski-metergram** [Dropsource/monarch#36]
When trying to install:
- `monarch 2.1.0`
- `mobx_codegen 2.0.5+2`

`pub get` fails with the following error:
```
Because mobx_codegen >=2.0.5 depends on analyzer ^3.0.0 and monarch >=2.0.0-pre.1 depends on analyzer ^2.3.0, mobx_codegen >=2.0.5 is incompatible with monarch >=2.0.0-pre.1.
```

**Comment by fertrig** [comment]
We will update the `monarch` package to support `analyzer 3.0.0` in the next few days. For now, you can use `mobx_codegen 2.0.4` to work with Monarch. 

Thanks for reporting this issue.

**Comment by fertrig** [comment]
Fix ready. Please use `monarch 2.2.0` to use `mobx_codegen 2.0.5+2`.
