### ISSUE TITLE
We could not find a compatible Monarch UI for this version of Monarch and Flutter.

### ISSUE THREAD

**Issue by kevalt-nt** [Dropsource/monarch#39]
Hey devs! 
i'm trying to run monarch but not able to do, it shows below mentioned error.

error : (here my output of monarch run)
---------------------------------------------------------------------------------------------------------
Using flutter sdk at C:\src\flutter\bin\flutter
Downloading the Monarch UI for this project's flutter version...
We could not find a compatible Monarch UI for this version of Monarch and Flutter.
You could try switching Flutter versions. Or, create a GitHub issue in the Monarch repo
and let us know which Flutter version your project is using:
https://github.com/Dropsource/monarch/issues
---------------------------------------------------------------------------------------------------------
Also i have tried with switching the other channels but i got there errors too..

here my current flutter version : 
---------------------------------------------------------------------------------------------------------
D:\Workspace\monarch_example>flutter --version
Flutter 2.11.0-0.0.pre.871 • channel master • https://github.com/flutter/flutter.git
Framework • revision 4f4c7816c3 (84 minutes ago) • 2022-03-14 07:35:07 +0100
Engine • revision 6239bfb884
Tools • Dart 2.17.0 (build 2.17.0-182.0.dev) • DevTools 2.11.1
---------------------------------------------------------------------------------------------------------

I have also tried on stable channel but it shows below error :
---------------------------------------------------------------------------------------------------------
D:\Workspace\monarch_example>monarch init
Using flutter sdk at C:\src\flutter\bin\flutter

## Join our newsletter
Sign up to receive low frequency emails on the latest Monarch updates,
features and news!

Enter email (optional):

## Stay in touch
- GitHub: https://github.com/Dropsource/monarch
- Twitter: https://twitter.com/monarch_app
- Newsletter: https://monarchapp.io/docs/community

## Initializing monarch_example with Monarch
Adding dev_dependencies `monarch` and `build_runner`...
Setting up build.yaml...
Creating sample stories in stories directory...
Adding .monarch directory to .gitignore...
Running "flutter pub get" in monarch_example...
The current Dart SDK version is 2.16.1.

Because monarch_example requires SDK version >=2.17.0-169.0.dev <3.0.0, version solving failed.
pub get failed (1; Because monarch_example requires SDK version >=2.17.0-169.0.dev <3.0.0, version solving failed.)

There were some errors during Monarch initialization:
===============================================================================
Error running `flutter pub get`.
===============================================================================

D:\Workspace\monarch_example>flutter --version
Flutter 2.10.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7e9793dee1 (12 days ago) • 2022-03-02 11:23:12 -0600
Engine • revision bd539267b4
Tools • Dart 2.16.1 • DevTools 2.9.2

---------------------------------------------------------------------------------------------------------
(please let me know if i'm making any mistakes) any help will be appreciable Thanks in advance

**Comment by fertrig** [comment]
Hi, Monarch supports stable, dev and beta flutter channels. When you use the stable channel please update the `environment` field in your pubspec.yaml to the following.

```
environment:
  sdk: ">=2.16.1 <3.0.0"
```

Monarch should work then.

**Comment by kevalt-nt** [comment]
Hey thanks for the quick reply.. really appreciate it..
I'll try this by today and will let you know the update
