### ISSUE TITLE
build_runner should allow running with additional flags

### ISSUE THREAD

**Issue by danilofuchs** [Dropsource/monarch#4]
We always run `build_runner` with `--delete-conflicting-outputs` so all of code generation is fresh, every time.

```
Starting Monarch

Preparing stories...
3.1sec elapsed, 0/2 tasks completed

[SEVERE] Conflicting outputs were detected and the build is unable to prompt for permission to remove them. These outputs must be removed manually or the build can be run with `--delete-conflicting-outputs`. The outputs are: lib/[path-to-freezed-class]

Preparing stories (code generation) failed. Exiting.
Re-run with the --verbose flag to get more information
```

**Comment by danilofuchs** [comment]
I was able to run `monarch run` after running `build_runner` manually

**Comment by fertrig** [comment]
Done. Please run `monarch upgrade`. Then you can run `monarch run --delete-conflicting-outputs`.

Let me know how it goes.

**Comment by romanr** [comment]
`monarch run --delete-conflicting-outputs` - This is the only way monarch works for me. Instead of passing it all the time maybe parameter should be baked in by default?

Otherwise I get this error and can't run:

```
Enabling Flutter for desktop

Starting Monarch.

Preparing stories...
[WARNING] Invalidated precompiled build script due to missing asset graph.

[SEVERE] Conflicting outputs were detected and the build is unable to prompt for permission to remove them. These outputs must be removed manually or the build can be run with `--delete-conflicting-outputs`. The outputs are: lib/src/exceptions/app_exception.freezed.dart

pub finished with exit code 78

3.1sec elapsed, 0/2 tasks completed
Preparing stories (code generation) failed. Exiting.
Re-run with the --verbose flag to get more information
Process did not finish successfully, exit code 78
```

**Comment by fertrig** [comment]
@romanr This error seems to be related to using both freezed and monarch. However, I was not able to reproduce it. I set up a test project with both freezed and monarch. I made various changes and it didn't require me to use the `--delete-conflicting-outputs`. Everything worked as expected without the flag.

Do you have steps I could use to reproduce the error you are getting?

For some reason, build_runner is not able to detect previous changes were made by freezed or monarch and it wants you to pass the `--delete-conflicting-outputs` flag.
