### ISSUE TITLE
Infinite running tasks

### ISSUE THREAD

**Issue by gdelataillade** [Dropsource/monarch#42]
# Infos
macOS Monterey 12.5.1
MacBook Pro M1 Pro
Xcode 14.0
Flutter 3.3.2
monarch: ^2.3.0
build_runner: ^2.1.0

# Description
I downloaded monarch and ran `monarch init` on my existing project.
Then I ran `monarch run`, which launched the UI but the loading is infinite:

<img width="400" alt="Screen Shot 2022-09-27 at 11 41 20" src="https://user-images.githubusercontent.com/32983806/192492499-ff828e85-d35e-4930-aa7f-80758df008dc.png">

When I take a look at the terminal, I see those 2 exceptions:

<img width="700" alt="Screen Shot 2022-09-27 at 11 44 02" src="https://user-images.githubusercontent.com/32983806/192493040-df101698-1476-4213-9754-692cd6922791.png">

After those 2 exceptions, there is this output repeating forever:

`20.3min elapsed, 0/1 tasks completed`

When I init and run monarch on a new Flutter project it works perfectly, but with my existing project I face this issue.
I guess there is probably a conflict with the packages I use.

# Dependencies

  ### Architecture
  get_it: ^7.2.0
  flutter_hooks: ^0.16.0
  get: 4.6.1
  event_bus: ^2.0.0

  ### Firebase
  firebase_auth: ^3.3.17
  firebase_core: ^1.16.0
  firebase_analytics: ^9.1.9
  firebase_image: ^1.1.1
  firebase_remote_config: ^2.0.12
  firebase_storage: ^10.2.15
  cloud_firestore: ^3.0.0
  firebase_storage_web: ^3.2.16
  firebase_core_web: ^1.6.4

  ### Service
  sentry_flutter: ^6.5.1
  amplitude_flutter: ^3.8.1
  flutter_local_notifications: ^9.4.0
  quick_actions: ^0.6.0+9
  flutter_stripe: ^4.0.0
  pay: ^1.0.10
  health: ^3.4.4
  widgetbook_annotation: ^2.0.2
  battery_plus: ^2.1.4+1
  flutter_downloader: ^1.8.1
  android_alarm_manager_plus: ^2.0.6+1
  mic_stream: ^0.6.2

  ### Audio / Video
  soundpool: ^2.3.0
  just_audio: ^0.9.20
  audio_service: ^0.18.4
  video_player: 2.4.5
  chewie:
    git:
      url: https://github.com/yelkamel/chewie_fullscreen_tmp
  agora_rtc_engine:
    git:
      url: https://github.com/AgoraIO/Agora-Flutter-SDK.git
      ref: dev/flutter-upgrade-3.0

  ### UI / UX
  auto_size_text: ^3.0.0
  disk_space: ^0.2.1
  duration_picker: ^1.1.0+1
  easy_rich_text: ^1.0.4
  flutter_animation_progress_bar: ^2.0.1
  blobs: ^2.0.0
  flip_card: ^0.6.0
  flutter_keyboard_visibility: ^5.1.1
  step_progress_indicator: ^1.0.2
  flutter_time_picker_spinner: ^2.0.0
  modal_bottom_sheet: ^2.0.0
  sliding_up_panel: ^2.0.0+1
  sleek_circular_slider: ^2.0.1
  slide_to_act: ^2.0.1
  scrollable_positioned_list: ^0.2.3
  fancy_shimmer_image: ^2.0.1+1
  smooth_page_indicator: ^1.0.0+2
  configurable_expansion_tile_null_safety: ^2.0.2
  scroll_to_index: ^3.0.1
  flutter_audio_waveforms: ^1.2.1+6
  flutter_login_funnel:
    git:
      url: https://github.com/yelkamel/flutter_login_funnel
  loop_page_view: ^1.2.0

  ### Tools
  intl: ^0.17.0
  flutter_svg: ^1.0.3
  http: ^0.13.1
  http_auth: ^1.0.0
  lottie: ^1.2.0
  screenshot: ^1.2.3
  tap_debouncer: ^2.0.1
  url_launcher: ^6.0.3
  webview_flutter: ^3.0.0
  app_review: ^2.1.1+1
  flutter_fgbg: ^0.1.0
  social_share: ^2.2.1
  wakelock: ^0.6.1+2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.8
  permission_handler: ^10.0.0
  torch_controller: ^1.0.0
  add_2_calendar: ^2.1.2
  focus_detector: ^2.0.1

  system_settings:
    git:
      url: https://github.com/lp0int/system_settings
      ref: migrateToV2

  we_slide:
    git:
      url: https://github.com/yelkamel/we_slide

  countdown:
    git:
      url: https://github.com/cacianokroth/countdown
      ref: chore-migrate-to-support-nullsafety

  splash_tap:
    git:
      url: https://github.com/ARH-DEVS/splash_tap
      ref: null-safety

  firebase_analytics_web: ^0.4.0+14

# dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3
  lints: ^1.0.1
  build_runner: ^2.1.0
  widgetbook_generator: ^2.1.1
  widgetbook: ^2.2.1
  monarch: ^2.3.0

**Comment by fertrig** [comment]
Please make sure to pin the monarch package dependency to `2.3.0`.

```
dev_dependencies:
  ...
  monarch: 2.3.0
```

The run `flutter pub get` again.

For some reason the pub command is installing the pre release version of monarch.

Please let me know if that fixes your issue.

**Comment by yelkamel** [comment]
I got the same issue and it's work for me to pin the version to 2.3.0 

thanks @fertrig

**Comment by atsumo** [comment]
I got the same issue...
I can not pin monarch package to 2.3.0, because I use analyzer package 4.7.0 for other packages

```
monarch >=2.2.0 <2.4.0-pre.3 depends on analyzer >=2.3.0 <4.0.0
```

**Comment by fertrig** [comment]
@atsumo The new version of Monarch is out, please give it a try, it should solve your issue. You will need to run `monarch upgrade`. Then make sure the monarch dependency in your pubspec.yaml is set to 3.0.0.
