### ISSUE TITLE
 Monarch UI not downloading .....

### ISSUE THREAD

**Issue by xeron56** [Dropsource/monarch#44]
[log_monarch_cli.log](https://github.com/Dropsource/monarch/files/9973172/log_monarch_cli.log)
![image](https://user-images.githubusercontent.com/11449967/200888637-caca8de1-709b-48e8-9fcf-51b15dbd93ec.png)

**Comment by fertrig** [comment]
Monarch uses curl to download the UI binaries it needs for the flutter version you are running. On Windows, curl has issues if your network is using a MITM proxy. See the accepted answer [here](https://stackoverflow.com/questions/54938026/curl-unknown-error-0x80092012-the-revocation-function-was-unable-to-check-r).

To work around it, please run this command:

```
curl -O  https://d1sjtjbeeitkk.cloudfront.net/windows/1.7.8/monarch_ui_1.7.8_flutter_windows_3.3.7-stable.zip --ssl-no-revoke
```

Then copy the downloaded zip file to your monarch_ui directory, which from your logs is at `C:\monarch\bin\cache\monarch_ui`.

Then unzip `monarch_ui_1.7.8_flutter_windows_3.3.7-stable.zip` inside the monarch_ui directory. You should end up with a directory `C:\monarch\bin\cache\monarch_ui\flutter_windows_3.3.7-stable` which has a `monarch_windows_app.exe` inside of it.

Now, you should be able to do `monarch run` inside your flutter project.

We'll work on a permanent fix for the next version of Monarch.
