### ISSUE TITLE
code changes don't reload monarch

### ISSUE THREAD

**Issue by filly82** [Dropsource/monarch#47]
`Target copy_flutter_bundle failed: Exception: Flutter failed to copy ..\f_common_widgets_flutter\.dart_tool\flutter_build\0cf
2e1c3577630af4f31f6666d4b20e1\app.dill to .monarch\flutter_assets\kernel_blob.bin due to unknown error. The flutter tool cannot access the file or directory.
Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the current user.`

any ideas?

**Comment by filly82** [comment]
when not running monarch from a terminal within my IDE than it works

**Comment by fertrig** [comment]
I'll try it. Which IDE do you use?

**Comment by filly82** [comment]
Android Studio

**Comment by filly82** [comment]
Yes I am, but the problem does not occur any more. Sorry for the incovenience. Closing the issue
