### ISSUE TITLE
Readme.md Missing dependencies for Windows / mac

### ISSUE THREAD

**Issue by detroxx92** [Dropsource/monarch#5]
While trying to use the monarch app on windows i could not get the monarch UI started.
I figured out that i was missing the desktop C++ support for Visual Studio (flutter  doctor).

Maybe set a note to the readme and the website. This could help :)

**Comment by fertrig** [comment]
You are correct. Working on it now.

**Comment by fertrig** [comment]
Added to the install instructions: https://monarchapp.io/docs/install

Thank you for creating this issue!
