### ISSUE TITLE
More samples in the documentation

### ISSUE THREAD

**Issue by gcostaapps** [Dropsource/monarch#6]
First I want to thank you for opening this amazing tool, the documentation is very good too, I think it's the best from these tools that mimic Storybook.

I saw in Reddit that you are planning to release some sample projects and I think it would be of great value for the community.

I'm opening this issue so this can be tracked and also to say that I'm open to help with the docs if needed.

**Comment by fertrig** [comment]
You're very welcome and thank you for your kind words!

We are currently working on a sample project to show how Monarch can work with:

- The Bloc pattern
- The Provider pattern
- Internationalization
- Custom themes
- Different UI interactions, like Modals, nav bars, etc.

We'll update this issue once we publish the sample project.

**Comment by fertrig** [comment]
Monarch samples project is ready! 🚀

https://github.com/Dropsource/monarch_samples

**Comment by gcostaapps** [comment]
Awesome! Thank you for the samples
