### ISSUE TITLE
Pass parameters to widgets

### ISSUE THREAD

**Issue by leisim** [Dropsource/monarch#7]
This is a very promising project. It would be awesome if it was possible to define parameters that can be passed to widgets and changed in monach to test different configurations of a widget.

For example like this:
```dart
Widget textWidget(Color textColor) => Text('I am a Text widget', style: TextStyle(color: textColor));
```

**Comment by fertrig** [comment]
We agree that it would be nice to change those parameter on the UI. Currently, you can do that in code:
```
Text textWidget(Color textColor) =>
    Text('I am a Text widget', style: TextStyle(color: textColor));

Widget red() => textWidget(Colors.red);
Widget yellow() => textWidget(Colors.yellow);
Widget blue() => textWidget(Colors.blue);
```
You will then see red, yellow and blue as stories in the Monarch UI. As you change the colors in code, the Monarch UI will reflect the changes automatically. The feedback is fast enough once you get going.

Future versions of Monarch will let you change that on the Monarch UI so you can play with stories live.
