### ISSUE TITLE
Add .monarch directory to git ignore if git repository detected in project root

### ISSUE THREAD

**Issue by bkraszewski** [Dropsource/monarch#9]
I noticed using monarch init creates temp directory .monarch/* in the project root. if possible, can script append 

.monarch/* 

to git ignore if project root has git initialized?

**Comment by fertrig** [comment]
`monarch init` has been doing that. Please make sure you run `monarch upgrade` to get latest monarch binaries. You can also use `monarch --version` to check what version you are running.

Releases can be found [here](https://monarchapp.io/blog). We'll update that page every time we do a new release.
